# Generated by Django 4.2.9 on 2024-01-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('fin_code', models.CharField(default=None, max_length=15, primary_key=True, serialize=False)),
                ('fnc_name', models.CharField(default=None, max_length=255)),
                ('fees_charges_name', models.CharField(default=None, max_length=255)),
                ('dsm_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sras_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('tras_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('react_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('l1_phone', models.IntegerField(blank=True, default=None, null=True)),
                ('l2_phone', models.IntegerField(blank=True, default=None, null=True)),
                ('l1_mail', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('l2_mail', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'registration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.IntegerField(blank=True, default=None, null=True)),
                ('bank_name', models.CharField(default=None, max_length=255)),
                ('ifsc_code', models.CharField(default=None, max_length=12)),
                ('is_sbi', models.BooleanField(default=None)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('supporting_docs', models.URLField(blank=True, default=None, null=True)),
                ('fin_code_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.registration')),
            ],
            options={
                'db_table': 'bank_details',
                'managed': True,
            },
        ),
    ]
