# Generated by Django 4.2.9 on 2024-01-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='fnc_name',
            new_name='finance_name',
        ),
    ]
