# Generated by Django 4.2.9 on 2024-01-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_fnc_name_registration_finance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='entity_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
