# Generated by Django 4.2.9 on 2024-01-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_entity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='l1_phone',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='l2_phone',
        ),
    ]
