# Generated by Django 4.2.9 on 2024-01-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_registration_l1_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='l1_phone',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='l2_phone',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='l1_mail',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='l2_mail',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
