# Generated by Django 4.2.9 on 2024-01-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registration_l1_phone_registration_l2_phone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankdetails',
            unique_together={('bank_account', 'fin_code_fk')},
        ),
    ]
