# Generated by Django 4.2.9 on 2024-01-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_bankdetails_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField(default=None)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('srpc_fetch_status', models.BooleanField(default=False)),
                ('fetched_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'year_calendar',
                'managed': True,
                'unique_together': {('week_no', 'start_date')},
            },
        ),
    ]
