# Generated by Django 4.2.9 on 2024-01-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_yearcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='fin_year',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
