# Generated by Django 4.2.9 on 2024-01-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_yearcalendar_fin_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_date', models.DateField(default=None)),
                ('description', models.TextField(default=None)),
                ('ref_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('branch_code', models.CharField(default=None, max_length=255)),
                ('debit', models.FloatField(blank=True, default=None, null=True)),
                ('credit', models.FloatField(blank=True, default=None, null=True)),
                ('balance', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'bank_statement',
                'managed': True,
            },
        ),
    ]
