# Generated by Django 4.2.9 on 2024-01-25 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_bankstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='is_identified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='record_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
