# Generated by Django 4.2.9 on 2024-01-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_bankstatement_is_identified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='bank_type',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
