# Generated by Django 4.2.9 on 2024-02-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_bankstatement_bank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='folder_path',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
