# Generated by Django 4.2.9 on 2024-02-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_yearcalendar_folder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='bills_uploaded_status',
            field=models.BooleanField(default=False),
        ),
    ]
