# Generated by Django 4.2.9 on 2024-02-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_yearcalendar_bills_uploaded_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ent_type',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='filename',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_nclt',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
