# Generated by Django 4.2.9 on 2024-02-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_registration_ent_type_registration_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='is_nclt',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
