# Generated by Django 4.2.9 on 2024-02-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_alter_registration_is_nclt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='ent_type',
        ),
    ]
