# Generated by Django 4.2.9 on 2024-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_remove_registration_ent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fin_code',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('fin_code', 'start_date', 'end_date')},
        ),
    ]
