# Generated by Django 4.2.9 on 2024-02-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_registration_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_code', models.CharField(default=None, max_length=15)),
                ('finance_name', models.CharField(default=None, max_length=255)),
                ('fees_charges_name', models.CharField(default=None, max_length=255)),
                ('dsm_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sras_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('tras_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('react_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('entity_type', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('l1_phone', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('l2_phone', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('l1_mail', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('l2_mail', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('is_nclt', models.BooleanField(blank=True, default=None, null=True)),
                ('filename', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'registration',
                'managed': True,
                'unique_together': {('fin_code', 'start_date', 'end_date')},
            },
        ),
    ]
