# Generated by Django 4.2.9 on 2024-02-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.IntegerField(blank=True, default=None, null=True)),
                ('bank_name', models.CharField(default=None, max_length=255)),
                ('ifsc_code', models.CharField(default=None, max_length=12)),
                ('is_sbi', models.BooleanField(default=None)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('supporting_docs', models.URLField(blank=True, default=None, null=True)),
                ('fin_code_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.registration')),
            ],
            options={
                'db_table': 'bank_details',
                'managed': True,
                'unique_together': {('bank_account', 'fin_code_fk')},
            },
        ),
    ]
