# Generated by Django 4.2.9 on 2024-03-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='gst',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='pan_card',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
