# Generated by Django 4.2.9 on 2024-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_bankdetails_gst_bankdetails_pan_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_account',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
