# Generated by Django 4.2.9 on 2024-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_alter_bankdetails_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_account',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
