# Generated by Django 4.2.9 on 2024-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_alter_bankdetails_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='gst',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='pan_card',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
