# Generated by Django 4.2.9 on 2024-03-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_alter_bankdetails_gst_alter_bankdetails_pan_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='supporting_docs',
        ),
    ]
