# Generated by Django 4.2.9 on 2024-03-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_remove_bankdetails_supporting_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='supporting_docs',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
