# Generated by Django 4.2.9 on 2024-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_bankdetails_supporting_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='remarks',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
