# Generated by Django 4.2.9 on 2024-03-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_registration_remarks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('fin_code', 'end_date')},
        ),
    ]
