# Generated by Django 4.2.9 on 2024-03-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_alter_registration_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolAccountTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_types', models.CharField(default=None, max_length=50)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'poolaccount_types',
                'managed': True,
            },
        ),
    ]
