# Generated by Django 4.2.9 on 2024-03-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_poolaccounttypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='dsm_bills_uploaded_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yearcalendar',
            name='mbas_bills_uploaded_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yearcalendar',
            name='reac_bills_uploaded_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yearcalendar',
            name='sras_bills_uploaded_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yearcalendar',
            name='tras_bills_uploaded_status',
            field=models.BooleanField(default=False),
        ),
    ]
