# Generated by Django 4.2.9 on 2024-03-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_yearcalendar_dsm_bills_uploaded_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearcalendar',
            old_name='bills_uploaded_status',
            new_name='ir_bills_uploaded_status',
        ),
    ]
