# Generated by Django 4.2.11 on 2024-03-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_rename_bills_uploaded_status_yearcalendar_ir_bills_uploaded_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankStatement',
        ),
    ]
