# Generated by Django 4.2.11 on 2024-04-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_bankshortnamemappings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankshortnamemappings',
            old_name='short_name',
            new_name='short_name1',
        ),
    ]
