# Generated by Django 4.2.11 on 2024-04-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_rename_short_name_bankshortnamemappings_short_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankshortnamemappings',
            name='is_ib',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='bankshortnamemappings',
            name='is_sbi',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='bankshortnamemappings',
            name='short_name2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankshortnamemappings',
            name='short_name3',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankshortnamemappings',
            name='short_name1',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
