# Generated by Django 4.2.11 on 2024-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_disbursementdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRPCInputFileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default=None, max_length=100)),
                ('pool_acc', models.CharField(default=None, max_length=50)),
                ('enddate', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
