# Generated by Django 4.2.11 on 2024-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_srpcinputfilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(default=None)),
                ('enddate', models.DateField(blank=True, default=None, null=True)),
                ('dsm', models.IntegerField(default=None)),
                ('sras', models.IntegerField(default=None)),
                ('tras', models.IntegerField(default=None)),
                ('mbas', models.IntegerField(default=None)),
                ('ir', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'disbursement_order',
                'managed': True,
            },
        ),
    ]
