# Generated by Django 4.2.11 on 2024-04-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_poolduedates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DueDates',
        ),
    ]
