# Generated by Django 4.2.11 on 2024-04-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_delete_duedates'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementorder',
            name='reac',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='poolduedates',
            name='reac',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
