# Generated by Django 4.2.11 on 2024-05-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_disbursementorder_reac_poolduedates_reac'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementorder',
            name='prewk',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
