# Generated by Django 4.2.11 on 2024-05-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_disbursementorder_prewk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementorder',
            name='prewk',
        ),
    ]
