# Generated by Django 4.2.11 on 2024-05-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_remove_disbursementorder_prewk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_accounts', models.CharField(default=None, max_length=255)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'merged_accounts',
                'managed': True,
            },
        ),
    ]
