# Generated by Django 4.2.11 on 2024-05-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_mergedaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='netas_bills_uploaded_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
