# Generated by Django 4.2.11 on 2024-05-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0046_yearcalendar_netas_bills_uploaded_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementorder',
            name='mbas',
        ),
        migrations.RemoveField(
            model_name='disbursementorder',
            name='sras',
        ),
        migrations.RemoveField(
            model_name='disbursementorder',
            name='tras',
        ),
        migrations.AddField(
            model_name='disbursementorder',
            name='net_as',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
