# Generated by Django 4.2.11 on 2024-05-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_remove_disbursementorder_mbas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='scuc_bills_uploaded_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
