# Generated by Django 4.2.11 on 2024-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_yearcalendar_scuc_bills_uploaded_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankshortnamemappings',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
