# Generated by Django 4.2.11 on 2024-06-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_bankshortnamemappings_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankshortnamemappings',
            name='bank_type',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
