# Generated by Django 4.2.11 on 2024-06-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0050_bankshortnamemappings_bank_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankshortnamemappings',
            name='is_ib',
        ),
        migrations.RemoveField(
            model_name='bankshortnamemappings',
            name='is_sbi',
        ),
    ]
