# Generated by Django 4.2.11 on 2024-06-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0051_remove_bankshortnamemappings_is_ib_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankshortnamemappings',
            name='short_names',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
