# Generated by Django 4.2.11 on 2024-06-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0052_bankshortnamemappings_short_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='beneficiary_name',
            field=models.CharField(default=None, max_length=255,blank=True,null=True),
        ),
    ]
