# Generated by Django 4.2.11 on 2024-07-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0053_bankdetails_beneficiary_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankshortnamemappings',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='bankshortnamemappings',
            name='start_date',
        ),
    ]
