# Generated by Django 4.2.11 on 2024-07-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0054_remove_bankshortnamemappings_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankshortnamemappings',
            unique_together={('fin_code',)},
        ),
    ]
