# Generated by Django 4.2.11 on 2024-08-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0055_alter_bankshortnamemappings_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcalendar',
            name='cong_bills_uploaded_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
