# Generated by Django 4.2.11 on 2024-08-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0056_yearcalendar_cong_bills_uploaded_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolduedates',
            name='cong',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
