# Generated by Django 4.2.11 on 2024-08-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0057_poolduedates_cong'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementorder',
            name='cong',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
