# Generated by Django 4.2.11 on 2025-02-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0058_disbursementorder_cong'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('user_id', models.IntegerField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
    ]
