# Generated by Django 4.2.11 on 2025-04-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0059_authtoken_authuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
