# Generated by Django 4.2.11 on 2025-06-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0060_registration_username'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='LCDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fincode', models.CharField(default=None, max_length=25)),
                ('new_existing', models.CharField(default=None, max_length=25)),
                ('ref_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('amount_inlacs', models.FloatField(default=None)),
                ('date_of_issue', models.DateField(default=None)),
                ('date_of_expiry', models.DateField(blank=True, default=None, null=True)),
                ('supporting_docs', models.TextField(blank=True, default=None, null=True)),
                ('remarks', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lc_details',
                'managed': True,
                'unique_together': {('fincode', 'date_of_issue')},
            },
        ),
    ]
