# Generated by Django 4.2.11 on 2025-06-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0061_rldcemployees_lcdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='RLDCEmployees',
            fields=[
                ('empname', models.CharField(default=None, max_length=255)),
                ('empdept', models.CharField(default=None, max_length=50)),
                ('empid', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('emp_signature', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('emp_designation', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'rldc_employees',
            },
        ),
    ]
