# Generated by Django 4.2.11 on 2025-06-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0062_rldcemployees'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcdetails',
            name='delayed_weeks',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lcdetails',
            name='is_opened',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='lcdetails',
            name='lc_amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lcdetails',
            name='payable_weeks',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lcdetails',
            name='sbi_concurrence',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='lcdetails',
            name='total_payable',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
