# Generated by Django 4.2.9 on 2024-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(blank=True, max_length=15)),
                ('Week_no', models.IntegerField(blank=True)),
                ('Consider_Year', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('Consider_Week_no', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Week_startdate', models.DateField(default=None)),
                ('Week_enddate', models.DateField(default=None)),
                ('Revision_no', models.CharField(default=None, max_length=15)),
                ('Letter_date', models.DateField(default=None)),
                ('Due_date', models.DateField(default=None)),
                ('Disbursement_date', models.DateField(default=None)),
                ('Lc_date', models.DateField(default=None)),
                ('Interest_levydate', models.DateField(default=None)),
                ('Entity', models.TextField(default=None)),
                ('Under_drawl_charges', models.FloatField(blank=True, default=None)),
                ('Over_drawl_charges', models.FloatField(blank=True, default=None)),
                ('Postfacto_charges', models.FloatField(blank=True, default=0)),
                ('Final_charges', models.FloatField(blank=True, default=None)),
                ('Outstanding', models.BigIntegerField(blank=True, default=0)),
                ('PayableorReceivable', models.CharField(blank=True, default=None, max_length=50)),
                ('Remarks', models.TextField(blank=True, default=None, null=True)),
                ('registration_id', models.CharField(default=None, max_length=100)),
                ('Pay_type', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('Bank_type', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('Pay_refno', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Paid_date', models.DateField(default=None)),
                ('Paid_amount', models.FloatField(blank=True)),
                ('Status', models.CharField(default='Notified', max_length=20)),
            ],
            options={
                'unique_together': {('Fin_year', 'Week_no', 'registration_id')},
            },
        ),
    ]
