# Generated by Django 4.2.9 on 2024-03-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acc_type', models.CharField(default=None, max_length=50)),
                ('Fin_year', models.CharField(blank=True, max_length=10)),
                ('Week_no', models.IntegerField(blank=True)),
                ('Entity', models.CharField(default=None, max_length=500)),
                ('Fin_code', models.CharField(default=None, max_length=15)),
            ],
            options={
                'unique_together': {('Acc_type', 'Fin_year', 'Week_no', 'Fin_code')},
            },
        ),
    ]
