# Generated by Django 4.2.9 on 2024-03-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0002_temporarymatched'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temporarymatched',
            table='temporary_matched',
        ),
    ]
