# Generated by Django 4.2.9 on 2024-03-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0003_alter_temporarymatched_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigureModel',
            new_name='DSMBaseModel',
        ),
        migrations.AlterModelTable(
            name='dsmbasemodel',
            table='dsm_basemodel',
        ),
    ]
