# Generated by Django 4.2.9 on 2024-03-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0004_rename_configuremodel_dsmbasemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarymatched',
            name='DevFinal',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='temporarymatched',
            name='PayRcv',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
