# Generated by Django 4.2.9 on 2024-03-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0005_temporarymatched_devfinal_temporarymatched_payrcv'),
    ]

    operations = [

    ]
