# Generated by Django 4.2.9 on 2024-03-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0006_alter_temporarymatched_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temporarymatched',
            unique_together={('Acc_type', 'Fin_year', 'Week_no', 'Entity')},
        ),
    ]
