# Generated by Django 4.2.9 on 2024-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0007_alter_temporarymatched_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryInterRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(blank=True, max_length=10)),
                ('Week_no', models.IntegerField(blank=True)),
                ('WRSR', models.FloatField(blank=True, default=None)),
                ('ERSR', models.FloatField(blank=True, default=None)),
                ('WRWR', models.FloatField(blank=True, default=None)),
                ('ERER', models.FloatField(blank=True, default=None)),
                ('DevFinal', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('PayRcv', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'db_table': 'temporary_interregional',
                'unique_together': {('Fin_year', 'Week_no')},
            },
        ),
    ]
