# Generated by Django 4.2.9 on 2024-03-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0008_temporaryinterregional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryinterregional',
            name='DevFinal',
        ),
        migrations.RemoveField(
            model_name='temporaryinterregional',
            name='PayRcv',
        ),
    ]
