# Generated by Django 4.2.9 on 2024-03-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0009_remove_temporaryinterregional_devfinal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryinterregional',
            name='ERER',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryinterregional',
            name='ERSR',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryinterregional',
            name='Fin_year',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='temporaryinterregional',
            name='WRSR',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryinterregional',
            name='WRWR',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryinterregional',
            name='Week_no',
            field=models.IntegerField(default=None),
        ),
    ]
