# Generated by Django 4.2.9 on 2024-03-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0010_alter_temporaryinterregional_erer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryinterregional',
            name='Revision_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='temporarymatched',
            name='Revision_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
