# Generated by Django 4.2.9 on 2024-03-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0011_temporaryinterregional_revision_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsmbasemodel',
            old_name='registration_id',
            new_name='Fin_code',
        ),
        migrations.AlterUniqueTogether(
            name='dsmbasemodel',
            unique_together={('Fin_year', 'Week_no', 'Fin_code')},
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Bank_type',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Outstanding',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Over_drawl_charges',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Paid_amount',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Paid_date',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Pay_refno',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Pay_type',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Postfacto_charges',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Under_drawl_charges',
        ),
    ]
