# Generated by Django 4.2.9 on 2024-03-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0012_rename_registration_id_dsmbasemodel_fin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsmbasemodel',
            name='Disbursement_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dsmbasemodel',
            name='Due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dsmbasemodel',
            name='Interest_levydate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dsmbasemodel',
            name='Lc_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dsmbasemodel',
            name='Letter_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
