# Generated by Django 4.2.9 on 2024-03-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0013_alter_dsmbasemodel_disbursement_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dsmbasemodel',
            unique_together={('Fin_year', 'Week_no', 'Entity')},
        ),
    ]
