# Generated by Django 4.2.9 on 2024-03-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0015_remove_dsmbasemodel_revision_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsmbasemodel',
            name='Revision_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
