# Generated by Django 4.2.9 on 2024-03-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0016_dsmbasemodel_revision_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryinterregional',
            old_name='Revision_no',
            new_name='WR_Revision_no',
        ),
    ]
