# Generated by Django 4.2.9 on 2024-03-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0017_rename_revision_no_temporaryinterregional_wr_revision_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryinterregional',
            name='ER_Revision_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
