# Generated by Django 4.2.9 on 2024-03-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0018_temporaryinterregional_er_revision_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temporaryinterregional',
            unique_together=set(),
        ),
    ]
