# Generated by Django 4.2.9 on 2024-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0019_alter_temporaryinterregional_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsmbasemodel',
            name='Applicable_enddate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dsmbasemodel',
            name='Applicable_startdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
