# Generated by Django 4.2.9 on 2024-03-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0020_dsmbasemodel_applicable_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(blank=True, max_length=15)),
                ('Week_no', models.IntegerField(blank=True)),
                ('Consider_Year', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('Consider_Week_no', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Week_startdate', models.DateField(default=None)),
                ('Week_enddate', models.DateField(default=None)),
                ('Applicable_startdate', models.DateField(blank=True, default=None, null=True)),
                ('Applicable_enddate', models.DateField(blank=True, default=None, null=True)),
                ('Revision_no', models.IntegerField(blank=True, default=None, null=True)),
                ('Letter_date', models.DateField(blank=True, default=None, null=True)),
                ('Due_date', models.DateField(blank=True, default=None, null=True)),
                ('Disbursement_date', models.DateField(blank=True, default=None, null=True)),
                ('Lc_date', models.DateField(blank=True, default=None, null=True)),
                ('Interest_levydate', models.DateField(blank=True, default=None, null=True)),
                ('Entity', models.TextField(default=None)),
                ('Final_charges', models.FloatField(blank=True, default=None)),
                ('PayableorReceivable', models.CharField(blank=True, default=None, max_length=50)),
                ('Remarks', models.TextField(blank=True, default=None, null=True)),
                ('Fin_code', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'ir_basemodel',
                'unique_together': {('Fin_year', 'Week_no', 'Entity')},
            },
        ),
    ]
