# Generated by Django 4.2.9 on 2024-03-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0021_irbasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarymatched',
            name='Is_infirm',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
