# Generated by Django 4.2.11 on 2024-03-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0023_bankstatement_mappedbankentries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatement',
            name='Balance',
        ),
    ]
