# Generated by Django 4.2.11 on 2024-03-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0024_remove_bankstatement_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='Balance',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
