# Generated by Django 4.2.11 on 2024-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0025_bankstatement_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappedbankentries',
            name='Entity',
            field=models.CharField(blank=True, default=None, max_length=350, null=True),
        ),
    ]
