# Generated by Django 4.2.11 on 2024-03-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0026_mappedbankentries_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='SplitStatus',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
