# Generated by Django 4.2.11 on 2024-03-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0027_bankstatement_splitstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappedbankentries',
            name='Other_info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
