# Generated by Django 4.2.11 on 2024-04-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0028_alter_mappedbankentries_other_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappedbankentries',
            name='Reject_remarks',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mappedbankentries',
            name='Status',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
