# Generated by Django 4.2.11 on 2024-04-10 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0030_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='approved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
