# Generated by Django 4.2.11 on 2024-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0031_payments_approved_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Week_no', models.IntegerField(blank=True, default=None, null=True)),
                ('Disbursed_date', models.DateField(default=None)),
            ],
            options={
                'db_table': 'disbursement_status',
            },
        ),
    ]
