# Generated by Django 4.2.11 on 2024-04-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0032_disbursementstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementstatus',
            name='Surplus_amt',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
