# Generated by Django 4.2.11 on 2024-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0034_dsmreceivables'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsmbasemodel',
            name='Disbursement_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
