# Generated by Django 4.2.11 on 2024-04-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0035_dsmbasemodel_disbursement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementstatus',
            name='Fin_year',
        ),
        migrations.RemoveField(
            model_name='disbursementstatus',
            name='Week_no',
        ),
    ]
