# Generated by Django 4.2.11 on 2024-04-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0036_remove_disbursementstatus_fin_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Applicable_enddate',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Applicable_startdate',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Consider_Week_no',
        ),
        migrations.RemoveField(
            model_name='dsmbasemodel',
            name='Consider_Year',
        ),
    ]
