# Generated by Django 4.2.11 on 2024-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0037_remove_dsmbasemodel_applicable_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementstatus',
            name='dsm',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='disbursementstatus',
            name='mbas',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='disbursementstatus',
            name='sras',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='disbursementstatus',
            name='tras',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
