# Generated by Django 4.2.11 on 2024-04-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0038_disbursementstatus_dsm_disbursementstatus_mbas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursedEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.CharField(blank=True, max_length=15)),
                ('week_no', models.IntegerField(blank=True)),
                ('entity', models.TextField(default=None)),
                ('final_charges', models.FloatField(default=None)),
                ('pool_acctype', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('disstatus_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.disbursementstatus')),
            ],
            options={
                'db_table': 'disbursed_entities',
            },
        ),
    ]
