# Generated by Django 4.2.11 on 2024-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0039_disbursedentities'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursedentities',
            name='fin_code',
            field=models.CharField(default=None),
        ),
    ]
