# Generated by Django 4.2.11 on 2024-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0041_alter_disbursementstatus_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursementstatus',
            name='dsm',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='disbursementstatus',
            name='mbas',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='disbursementstatus',
            name='sras',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='disbursementstatus',
            name='tras',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
