# Generated by Django 4.2.11 on 2024-04-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0042_alter_disbursementstatus_dsm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsmbasemodel',
            name='Fully_disbursed',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
