# Generated by Django 4.2.11 on 2024-04-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0043_dsmbasemodel_fully_disbursed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsmbasemodel',
            old_name='Disbursement_status',
            new_name='Is_disbursed',
        ),
    ]
