# Generated by Django 4.2.11 on 2024-04-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0044_rename_disbursement_status_dsmbasemodel_is_disbursed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DSMReceivables',
        ),
    ]
