# Generated by Django 4.2.11 on 2024-04-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0046_dsmreceivables'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementstatus',
            name='dsm_collected',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='disbursementstatus',
            name='dsm_disbursed',
            field=models.FloatField(default=None, null=True),
        ),
    ]
