# Generated by Django 4.2.11 on 2024-04-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0047_disbursementstatus_dsm_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementstatus',
            name='ir',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
