# Generated by Django 4.2.11 on 2024-04-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0048_disbursementstatus_ir'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursedentities',
            name='payrcv',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
