# Generated by Django 4.2.11 on 2024-04-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0050_srasbasemodel_sraspayments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRASReceivables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disbursed_amount', models.FloatField(blank=True, null=True)),
                ('rcvstatus_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.srasbasemodel')),
            ],
            options={
                'db_table': 'sras_receivables',
            },
        ),
    ]
