# Generated by Django 4.2.11 on 2024-04-30 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0052_mbasbasemodel_mbasreceivables_mbaspayments'),
    ]

    operations = [
        migrations.CreateModel(
            name='REACBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(blank=True, max_length=15)),
                ('Week_no', models.IntegerField(blank=True)),
                ('Week_startdate', models.DateField(default=None)),
                ('Week_enddate', models.DateField(default=None)),
                ('Revision_no', models.IntegerField(blank=True, default=None, null=True)),
                ('Letter_date', models.DateField(blank=True, default=None, null=True)),
                ('Due_date', models.DateField(blank=True, default=None, null=True)),
                ('Disbursement_date', models.DateField(blank=True, default=None, null=True)),
                ('Lc_date', models.DateField(blank=True, default=None, null=True)),
                ('Interest_levydate', models.DateField(blank=True, default=None, null=True)),
                ('Entity', models.TextField(default=None)),
                ('Final_charges', models.FloatField(blank=True, default=None)),
                ('PayableorReceivable', models.CharField(blank=True, default=None, max_length=50)),
                ('Remarks', models.TextField(blank=True, default=None, null=True)),
                ('Fin_code', models.CharField(default=None, max_length=100)),
                ('Is_disbursed', models.BooleanField(blank=True, default=None, null=True)),
                ('Fully_disbursed', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'db_table': 'reac_basemodel',
                'unique_together': {('Fin_year', 'Week_no', 'Entity')},
            },
        ),
        migrations.CreateModel(
            name='REACReceivables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disbursed_amount', models.FloatField(blank=True, null=True)),
                ('rcvstatus_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.reacbasemodel')),
            ],
            options={
                'db_table': 'reac_receivables',
            },
        ),
        migrations.CreateModel(
            name='REACPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid_date', models.DateField(default=None)),
                ('Description', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('Paid_amount', models.FloatField(blank=True)),
                ('Other_info', models.TextField(blank=True, default=None, null=True)),
                ('approved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paystatus_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.reacbasemodel')),
            ],
            options={
                'db_table': 'reac_payments',
            },
        ),
    ]
