# Generated by Django 4.2.11 on 2024-05-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0055_disbursementstatus_mbas_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursedentities',
            name='is_prevweeks',
            field=models.BooleanField(default=False),
        ),
    ]
