# Generated by Django 4.2.11 on 2024-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0057_remove_disbursementstatus_dsm_disbursed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementstatus',
            name='dsm_prevwk',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='disbursementstatus',
            name='mbas_prevwk',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='disbursementstatus',
            name='reac_prevwk',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='disbursementstatus',
            name='sras_prevwk',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='disbursementstatus',
            name='tras_prevwk',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
