# Generated by Django 4.2.11 on 2024-05-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0058_disbursementstatus_dsm_prevwk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementstatus',
            name='final_disburse',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
