# Generated by Django 4.2.11 on 2024-05-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0059_disbursementstatus_final_disburse'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursedentities',
            name='parent_table_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
