# Generated by Django 4.2.11 on 2024-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0060_disbursedentities_parent_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='BankType',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='IsSweep',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
