# Generated by Django 4.2.11 on 2024-05-10 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0061_bankstatement_banktype_bankstatement_issweep'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid_date', models.DateField(default=None)),
                ('Description', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('Paid_amount', models.FloatField(blank=True)),
                ('Other_info', models.TextField(blank=True, default=None, null=True)),
                ('approved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paystatus_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.irbasemodel')),
            ],
            options={
                'db_table': 'ir_payments',
            },
        ),
    ]
