# Generated by Django 4.2.11 on 2024-05-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0063_interestbasemodel_interestpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestbasemodel',
            name='Date_of_receipt',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
