# Generated by Django 4.2.11 on 2024-05-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0064_interestbasemodel_date_of_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestbasemodel',
            name='Amount_srpc_payabletopool',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
