# Generated by Django 4.2.11 on 2024-05-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0065_interestbasemodel_amount_srpc_payabletopool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestbasemodel',
            name='Amount_srpc_payabletopool',
        ),
    ]
