# Generated by Django 4.2.11 on 2024-05-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0069_interestbasemodel_no_of_days_delayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestbasemodel',
            name='Acc_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
