# Generated by Django 4.2.11 on 2024-05-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0070_interestbasemodel_acc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsmbasemodel',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='interestbasemodel',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mbasbasemodel',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reacbasemodel',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='srasbasemodel',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='trasbasemodel',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
