# Generated by Django 4.2.11 on 2024-05-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0071_alter_dsmbasemodel_is_disbursed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IomSerialNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iom_date', models.DateField(default=None)),
                ('dsm_iom_serial_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sras_iom_serial_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('tras_iom_serial_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('mbas_iom_serial_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('react_iom_serial_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('ir_iom_serial_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'iom_serialnos',
            },
        ),
    ]
