# Generated by Django 4.2.11 on 2024-05-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0072_iomserialno'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestpayments',
            name='Bank_type',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mbaspayments',
            name='Bank_type',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='Bank_type',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reacpayments',
            name='Bank_type',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sraspayments',
            name='Bank_type',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='traspayments',
            name='Bank_type',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
