# Generated by Django 4.2.11 on 2024-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0075_netasbasemodel_netaspayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='netasbasemodel',
            name='MBAS_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='netasbasemodel',
            name='REAC_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='netasbasemodel',
            name='SCUC_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='netasbasemodel',
            name='SRAS_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='netasbasemodel',
            name='TRAS_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
