# Generated by Django 4.2.11 on 2024-05-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0076_netasbasemodel_mbas_id_netasbasemodel_reac_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netasbasemodel',
            name='REAC_id',
        ),
    ]
