# Generated by Django 4.2.11 on 2024-05-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0078_disbursementstatus_net_as_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetASReceivables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disbursed_amount', models.FloatField(blank=True, null=True)),
                ('rcvstatus_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.netasbasemodel')),
            ],
            options={
                'db_table': 'netas_receivables',
            },
        ),
    ]
