# Generated by Django 4.2.11 on 2024-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0080_scucbasemodel_scucreceivables_scucpayments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcessBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(blank=True, max_length=15)),
                ('Week_no', models.IntegerField(blank=True)),
                ('Week_startdate', models.DateField(default=None)),
                ('Week_enddate', models.DateField(default=None)),
                ('Entity', models.TextField(default=None)),
                ('Final_charges', models.FloatField(blank=True, default=None)),
                ('PayableorReceivable', models.CharField(blank=True, default='Receivable', max_length=15)),
                ('Remarks', models.TextField(blank=True, default=None, null=True)),
                ('Fin_code', models.CharField(default=None, max_length=100)),
                ('Is_disbursed', models.BooleanField(blank=True, default=False, null=True)),
                ('Fully_disbursed', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'db_table': 'excess_basemodel',
                'unique_together': {('Fin_year', 'Week_no', 'Entity')},
            },
        ),
    ]
