# Generated by Django 4.2.11 on 2024-05-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0081_excessbasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsmbasemodel',
            name='Effective_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dsmbasemodel',
            name='Effective_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
