# Generated by Django 4.2.11 on 2024-05-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0082_dsmbasemodel_effective_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dsmbasemodel',
            unique_together=set(),
        ),
    ]
