# Generated by Django 4.2.11 on 2024-05-30 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0084_alter_dsmbasemodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Letter_date', models.DateField(default=None)),
                ('Acc_type', models.CharField(default=None, max_length=50)),
                ('Entity', models.TextField(default=None)),
                ('Final_charges', models.FloatField(blank=True, default=None)),
                ('PayableorReceivable', models.CharField(blank=True, default=None, max_length=50)),
                ('Remarks', models.TextField(blank=True, default=None, null=True)),
                ('Fin_code', models.CharField(default=None, max_length=100)),
                ('Is_disbursed', models.BooleanField(blank=True, default=False, null=True)),
                ('Fully_disbursed', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'db_table': 'revision_basemodel',
                'unique_together': {('Acc_type', 'Letter_date', 'Entity')},
            },
        ),
        migrations.CreateModel(
            name='RevisionPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid_date', models.DateField(default=None)),
                ('Description', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('Paid_amount', models.FloatField(blank=True)),
                ('Other_info', models.TextField(blank=True, default=None, null=True)),
                ('Bank_type', models.CharField(blank=True, default=None, null=True)),
                ('approved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paystatus_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.revisionbasemodel')),
            ],
            options={
                'db_table': 'revision_payments',
            },
        ),
    ]
