# Generated by Django 4.2.11 on 2024-05-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0085_revisionbasemodel_revisionpayments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dsmbasemodel',
            unique_together=set(),
        ),
    ]
