# Generated by Django 4.2.11 on 2024-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0087_alter_dsmbasemodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappedbankentries',
            name='Parent_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
