# Generated by Django 4.2.11 on 2024-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0088_mappedbankentries_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappedbankentries',
            name='Pool_Acc',
            field=models.CharField(default=None, max_length=55),
        ),
    ]
