# Generated by Django 4.2.11 on 2024-06-06 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0089_alter_mappedbankentries_pool_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRReceivables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disbursed_amount', models.FloatField(blank=True, null=True)),
                ('rcvstatus_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.irbasemodel')),
            ],
            options={
                'db_table': 'ir_receivables',
            },
        ),
    ]
