# Generated by Django 4.2.11 on 2024-06-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0090_irreceivables'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementstatus',
            name='ir_prevwk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
