# Generated by Django 4.2.11 on 2024-06-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0091_disbursementstatus_ir_prevwk'),
    ]

    operations = [
        migrations.AddField(
            model_name='irbasemodel',
            name='Fully_disbursed',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='irbasemodel',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
