# Generated by Django 4.2.11 on 2024-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0092_irbasemodel_fully_disbursed_irbasemodel_is_disbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='irpayments',
            name='Bank_type',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
