# Generated by Django 4.2.11 on 2024-06-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0093_irpayments_bank_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntimateNLDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intimate_date', models.DateField(default=None)),
                ('amount_available', models.FloatField(blank=True, default=None, null=True)),
                ('transfer_amount', models.FloatField(blank=True, default=None, null=True)),
                ('is_transferred', models.BooleanField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'intimate_nldc',
            },
        ),
    ]
