# Generated by Django 4.2.11 on 2024-06-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0094_intimatenldc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intimatenldc',
            unique_together={('intimate_date', 'amount_available')},
        ),
    ]
