# Generated by Django 4.2.11 on 2024-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0095_alter_intimatenldc_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intimatenldc',
            name='transfer_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
