# Generated by Django 4.2.11 on 2024-06-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0096_alter_intimatenldc_transfer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimatenldc',
            name='region',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
