# Generated by Django 4.2.11 on 2024-06-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0097_intimatenldc_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intimatenldc',
            old_name='region',
            new_name='region1',
        ),
        migrations.AddField(
            model_name='intimatenldc',
            name='region2',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='intimatenldc',
            name='region3',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='intimatenldc',
            name='region4',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
