# Generated by Django 4.2.11 on 2024-06-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0098_rename_region_intimatenldc_region1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intimatenldc',
            name='region1',
        ),
        migrations.RemoveField(
            model_name='intimatenldc',
            name='region2',
        ),
        migrations.RemoveField(
            model_name='intimatenldc',
            name='region3',
        ),
        migrations.RemoveField(
            model_name='intimatenldc',
            name='region4',
        ),
    ]
