# Generated by Django 4.2.11 on 2024-06-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0099_remove_intimatenldc_region1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimatenldc',
            name='er',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='intimatenldc',
            name='ner',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='intimatenldc',
            name='nr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='intimatenldc',
            name='psdf',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='intimatenldc',
            name='wr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
