# Generated by Django 4.2.11 on 2024-06-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0100_intimatenldc_er_intimatenldc_ner_intimatenldc_nr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimatenldc',
            name='is_used_indisbursement',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
