# Generated by Django 4.2.11 on 2024-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0101_intimatenldc_is_used_indisbursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCodeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.DateField(default=None)),
                ('receivable_to_pool', models.CharField(blank=True, default=None, null=True)),
                ('disbursement_from_pool', models.CharField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'accountcode_details',
            },
        ),
    ]
