# Generated by Django 4.2.11 on 2024-06-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0103_remove_accountcodedetails_acc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcodedetails',
            name='acc_type',
            field=models.CharField(default=None),
        ),
    ]
