# Generated by Django 4.2.11 on 2024-06-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0104_accountcodedetails_acc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsmreceivables',
            name='disbursed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dsmreceivables',
            name='iom_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dsmreceivables',
            name='neft_txnno',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
