# Generated by Django 4.2.11 on 2024-06-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0105_dsmreceivables_disbursed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsmreceivables',
            old_name='Disbursed_amount',
            new_name='disbursed_amount',
        ),
    ]
