# Generated by Django 4.2.11 on 2024-06-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0106_rename_disbursed_amount_dsmreceivables_disbursed_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srasreceivables',
            old_name='Disbursed_amount',
            new_name='disbursed_amount',
        ),
        migrations.AddField(
            model_name='srasreceivables',
            name='disbursed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='srasreceivables',
            name='iom_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='srasreceivables',
            name='neft_txnno',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
