# Generated by Django 4.2.11 on 2024-06-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0107_rename_disbursed_amount_srasreceivables_disbursed_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trasreceivables',
            old_name='Disbursed_amount',
            new_name='disbursed_amount',
        ),
        migrations.AddField(
            model_name='trasreceivables',
            name='disbursed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trasreceivables',
            name='iom_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trasreceivables',
            name='neft_txnno',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
