# Generated by Django 4.2.11 on 2024-06-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0108_rename_disbursed_amount_trasreceivables_disbursed_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Startdate', models.DateField(default=None)),
                ('Enddate', models.DateField(default=None)),
                ('Banktype', models.CharField(default=None, max_length=50)),
                ('Is_reconciled', models.BooleanField(default=None)),
            ],
            options={
                'db_table': 'bank_reconciliation',
                'unique_together': {('Startdate', 'Enddate', 'Banktype')},
            },
        ),
    ]
