# Generated by Django 4.2.11 on 2024-06-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0109_bankrecon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsmreceivables',
            old_name='disbursed_amount',
            new_name='Disbursed_amount',
        ),
    ]
