# Generated by Django 4.2.11 on 2024-06-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0110_rename_disbursed_amount_dsmreceivables_disbursed_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestbasemodel',
            name='Fully_disbursed',
        ),
        migrations.RemoveField(
            model_name='interestbasemodel',
            name='Is_disbursed',
        ),
    ]
