# Generated by Django 4.2.11 on 2024-06-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0111_remove_interestbasemodel_fully_disbursed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestBaseModel',
            new_name='TempInterestBaseModel',
        ),
        migrations.DeleteModel(
            name='InterestPayments',
        ),
    ]
