# Generated by Django 4.2.11 on 2024-06-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0112_rename_interestbasemodel_tempinterestbasemodel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tempinterestbasemodel',
            table='temp_interest_basemodel',
        ),
    ]
