# Generated by Django 4.2.11 on 2024-06-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0113_alter_tempinterestbasemodel_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempinterestbasemodel',
            unique_together={('Letter_date', 'Entity', 'Acc_type')},
        ),
    ]
