# Generated by Django 4.2.11 on 2024-06-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0117_alter_tempinterestbasemodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Letter_date', models.DateField(default=None)),
                ('Entity', models.CharField(default=None)),
                ('Amount', models.FloatField(blank=True, default=None)),
            ],
            options={
                'db_table': 'interest_basemodel',
                'unique_together': {('Letter_date', 'Entity')},
            },
        ),
    ]
