# Generated by Django 4.2.11 on 2024-06-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0118_interestbasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestbasemodel',
            name='Fin_code',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
