# Generated by Django 4.2.11 on 2024-06-27 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0119_interestbasemodel_fin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid_date', models.DateField(default=None)),
                ('Description', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('Paid_amount', models.FloatField(blank=True)),
                ('Other_info', models.TextField(blank=True, default=None, null=True)),
                ('Bank_type', models.CharField(blank=True, default=None, null=True)),
                ('Fin_code', models.CharField(default=None, max_length=50)),
                ('approved_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'interest_payments',
            },
        ),
    ]
