# Generated by Django 4.2.11 on 2024-06-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0120_interestpayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestbasemodel',
            old_name='Amount',
            new_name='Final_charges',
        ),
    ]
