# Generated by Django 4.2.11 on 2024-07-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0121_rename_amount_interestbasemodel_final_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intimatenldc',
            name='is_used_indisbursement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
