# Generated by Django 4.2.11 on 2024-07-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0122_alter_intimatenldc_is_used_indisbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimatenldc',
            name='file_path',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
