# Generated by Django 4.2.11 on 2024-07-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0123_intimatenldc_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intimatenldc',
            name='file_path',
        ),
    ]
