# Generated by Django 4.2.11 on 2024-07-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0124_remove_intimatenldc_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimatenldc',
            name='file_path',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
