# Generated by Django 4.2.11 on 2024-07-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0125_intimatenldc_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='netasreceivables',
            name='disbursed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='netasreceivables',
            name='iom_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='netasreceivables',
            name='neft_txnno',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
