# Generated by Django 4.2.11 on 2024-07-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0126_netasreceivables_disbursed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbasreceivables',
            name='disbursed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mbasreceivables',
            name='iom_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mbasreceivables',
            name='neft_txnno',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reacreceivables',
            name='disbursed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reacreceivables',
            name='iom_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reacreceivables',
            name='neft_txnno',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scucreceivables',
            name='disbursed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scucreceivables',
            name='iom_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scucreceivables',
            name='neft_txnno',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
