# Generated by Django 4.2.11 on 2024-07-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0127_mbasreceivables_disbursed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netasbasemodel',
            name='Revision_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
