# Generated by Django 4.2.11 on 2024-07-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0128_alter_netasbasemodel_revision_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsmbasemodel',
            name='Revision_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reacbasemodel',
            name='Revision_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scucbasemodel',
            name='Revision_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='srasbasemodel',
            name='Revision_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trasbasemodel',
            name='Revision_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
