# Generated by Django 4.2.11 on 2024-07-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0129_alter_dsmbasemodel_revision_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srasreceivables',
            old_name='disbursed_amount',
            new_name='Disbursed_amount',
        ),
        migrations.RenameField(
            model_name='trasreceivables',
            old_name='disbursed_amount',
            new_name='Disbursed_amount',
        ),
    ]
