# Generated by Django 4.2.11 on 2024-07-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0130_rename_disbursed_amount_srasreceivables_disbursed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scucbasemodel',
            name='Effective_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scucbasemodel',
            name='Effective_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='srasbasemodel',
            name='Effective_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='srasbasemodel',
            name='Effective_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trasbasemodel',
            name='Effective_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trasbasemodel',
            name='Effective_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
