# Generated by Django 4.2.11 on 2024-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0132_mbasbasemodel_effective_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionbasemodel',
            name='Effective_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='revisionbasemodel',
            name='Effective_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
