# Generated by Django 4.2.11 on 2024-07-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0133_revisionbasemodel_effective_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLDCPoolAmountSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disburse_date', models.DateField(default=None)),
                ('amount_for_dsm', models.FloatField(blank=True, default=None, null=True)),
                ('amount_for_netas', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'nldcpool_splitamount',
            },
        ),
    ]
