# Generated by Django 4.2.11 on 2024-07-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0134_nldcpoolamountsplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='nldcpoolamountsplit',
            name='is_disbursement_done',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='nldcpoolamountsplit',
            name='is_user_checked',
            field=models.BooleanField(default=None),
        ),
    ]
