# Generated by Django 4.2.11 on 2024-07-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0135_nldcpoolamountsplit_is_disbursement_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nldcpoolamountsplit',
            name='is_disbursement_done',
        ),
    ]
