# Generated by Django 4.2.11 on 2024-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0136_remove_nldcpoolamountsplit_is_disbursement_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='nldcpoolamountsplit',
            name='amount_for_reac',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
