# Generated by Django 4.2.11 on 2024-07-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0137_nldcpoolamountsplit_amount_for_reac'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimatenldc',
            name='notesheet_refno',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
