# Generated by Django 4.2.11 on 2024-07-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0138_intimatenldc_notesheet_refno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intimatenldc',
            name='notesheet_refno',
        ),
    ]
