# Generated by Django 4.2.11 on 2024-07-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0139_remove_intimatenldc_notesheet_refno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payments',
            unique_together={('Paid_date', 'Description', 'Paid_amount', 'paystatus_fk')},
        ),
    ]
