# Generated by Django 4.2.11 on 2024-07-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0140_alter_payments_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='netaspayments',
            unique_together={('Paid_date', 'Description', 'Paid_amount', 'paystatus_fk')},
        ),
    ]
