# Generated by Django 4.2.11 on 2024-07-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0142_alter_reacpayments_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='netasbasemodel',
            name='Effective_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='netasbasemodel',
            name='Effective_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
