# Generated by Django 4.2.11 on 2024-07-12 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0143_netasbasemodel_effective_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedIOMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iom_path', models.CharField(default=None, max_length=255)),
                ('iom_date', models.DateField(default=None)),
                ('uploaded_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'signed_ioms',
            },
        ),
    ]
