# Generated by Django 4.2.11 on 2024-07-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0144_signedioms'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedioms',
            name='acc_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
