# Generated by Django 4.2.11 on 2024-07-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0145_signedioms_acc_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mappedbankentries',
            unique_together={('Pool_Acc', 'Fin_year', 'Week_no', 'Entity', 'Amount', 'Status')},
        ),
    ]
