# Generated by Django 4.2.11 on 2024-07-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0146_alter_mappedbankentries_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbasbasemodel',
            name='Revision_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tempinterestbasemodel',
            name='Revision_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
