# Generated by Django 4.2.11 on 2024-07-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0147_alter_mbasbasemodel_revision_no_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='excessbasemodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='excessbasemodel',
            name='Fin_year',
        ),
        migrations.RemoveField(
            model_name='excessbasemodel',
            name='PayableorReceivable',
        ),
        migrations.RemoveField(
            model_name='excessbasemodel',
            name='Week_enddate',
        ),
        migrations.RemoveField(
            model_name='excessbasemodel',
            name='Week_no',
        ),
        migrations.RemoveField(
            model_name='excessbasemodel',
            name='Week_startdate',
        ),
    ]
