# Generated by Django 4.2.11 on 2024-07-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0148_alter_excessbasemodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excessbasemodel',
            name='Bank_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='excessbasemodel',
            name='Description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excessbasemodel',
            name='Other_info',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='excessbasemodel',
            name='Paid_date',
            field=models.DateField(default=None),
        ),
    ]
