# Generated by Django 4.2.11 on 2024-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0149_excessbasemodel_bank_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDisbursedWeeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_acctype', models.CharField(default=None, max_length=50)),
                ('fin_year', models.CharField(blank=True, max_length=15)),
                ('week_no', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'temp_disbursedweeks',
            },
        ),
    ]
