# Generated by Django 4.2.11 on 2024-07-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0150_tempdisbursedweeks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempdisbursedweeks',
            unique_together={('pool_acctype', 'fin_year', 'week_no')},
        ),
    ]
