# Generated by Django 4.2.11 on 2024-07-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0151_alter_tempdisbursedweeks_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mappedbankentries',
            unique_together=set(),
        ),
    ]
