# Generated by Django 4.2.11 on 2024-07-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0153_alter_mappedbankentries_unique_together'),
    ]

   
