# Generated by Django 4.2.11 on 2024-08-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0156_interestpayments_is_disbursed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid_amount', models.FloatField(default=None)),
                ('Is_disbursed', models.BooleanField(default=None)),
                ('Remarks', models.CharField(blank=True, default=None, max_length=255)),
            ],
            options={
                'db_table': 'other_paymentsmodel',
            },
        ),
    ]
