# Generated by Django 4.2.11 on 2024-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0157_otherpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpayments',
            name='Description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otherpayments',
            name='Paid_date',
            field=models.DateField(default=None),
        ),
    ]
