# Generated by Django 4.2.11 on 2024-08-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0158_otherpayments_description_otherpayments_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpayments',
            name='Bank_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
