# Generated by Django 4.2.11 on 2024-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0159_otherpayments_bank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementstatus',
            name='cong',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='disbursementstatus',
            name='cong_prevwk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
