# Generated by Django 4.2.11 on 2024-08-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0162_disbursementstatus_revision_disbursed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementstatus',
            name='revision_disbursed',
        ),
    ]
