# Generated by Django 4.2.11 on 2024-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0163_remove_disbursementstatus_revision_disbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementstatus',
            name='revision_disbursed',
            field=models.FloatField(default=None, null=True),
        ),
    ]
