# Generated by Django 4.2.11 on 2024-08-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0165_alter_revisionreceivables_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementstatus',
            name='remarks',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
