# Generated by Django 4.2.11 on 2024-08-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0166_disbursementstatus_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='excessbasemodel',
            name='Acc_Type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
