# Generated by Django 4.2.11 on 2024-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0168_payments_is_disbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='congpayments',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='irpayments',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='mbaspayments',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='netaspayments',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='reacpayments',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='revisionpayments',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sraspayments',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='traspayments',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
