# Generated by Django 4.2.11 on 2024-10-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0171_congbasemodel_legacy_dues_mbasbasemodel_legacy_dues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsmbasemodel',
            name='Legacy_dues',
            field=models.BooleanField(default=False),
        ),
    ]
