# Generated by Django 4.2.11 on 2024-11-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0173_alter_congbasemodel_legacy_dues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestpayments',
            name='Fin_code',
        ),
        migrations.AddField(
            model_name='interestpayments',
            name='paystatus_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.interestbasemodel'),
        ),
    ]
