# Generated by Django 4.2.11 on 2024-12-04 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0175_closingbalances'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fin_year', models.CharField(blank=True, max_length=15)),
                ('Week_no', models.IntegerField(blank=True, default=0, null=True)),
                ('Letter_date', models.DateField(blank=True, default=None, null=True)),
                ('Due_date', models.DateField(blank=True, default=None, null=True)),
                ('Entity', models.TextField(default=None)),
                ('Final_charges', models.FloatField(blank=True, default=None)),
                ('PayableorReceivable', models.CharField(blank=True, default=None, max_length=50)),
                ('Remarks', models.TextField(blank=True, default=None, null=True)),
                ('Fin_code', models.CharField(default=None, max_length=100)),
                ('Is_disbursed', models.BooleanField(blank=True, default=False, null=True)),
                ('Fully_disbursed', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Effective_start_date', models.DateField(blank=True, default=None, null=True)),
                ('Effective_end_date', models.DateField(blank=True, default=None, null=True)),
                ('Legacy_dues', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'legacy_basemodel',
                'unique_together': {('Fin_year', 'Week_no', 'Entity')},
            },
        ),
        migrations.CreateModel(
            name='LegacyPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid_date', models.DateField(default=None)),
                ('Description', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('Paid_amount', models.FloatField(blank=True)),
                ('Other_info', models.TextField(blank=True, default=None, null=True)),
                ('Bank_type', models.CharField(blank=True, default=None, null=True)),
                ('approved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Is_disbursed', models.BooleanField(blank=True, default=False, null=True)),
                ('paystatus_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.legacybasemodel')),
            ],
            options={
                'db_table': 'legacy_payments',
            },
        ),
    ]
