# Generated by Django 4.2.11 on 2024-12-10 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0176_legacybasemodel_legacypayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementstatus',
            name='legacy_staus',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='disbursementstatus',
            name='legacy_surplus_amt',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='LegacyIRPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid_date', models.DateField(default=None)),
                ('Description', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('Paid_amount', models.FloatField(blank=True)),
                ('Other_info', models.TextField(blank=True, default=None, null=True)),
                ('Bank_type', models.CharField(blank=True, default=None, null=True)),
                ('approved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Is_disbursed', models.BooleanField(blank=True, default=False, null=True)),
                ('paystatus_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.legacybasemodel')),
            ],
            options={
                'db_table': 'legacy_ir_payments',
            },
        ),
    ]
