# Generated by Django 4.2.11 on 2024-12-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0177_disbursementstatus_legacy_staus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacyIRPayments',
        ),
    ]
