# Generated by Django 4.2.11 on 2024-12-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0179_rename_legacy_staus_disbursementstatus_legacy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacybasemodel',
            name='Is_interregional',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
