# Generated by Django 4.2.11 on 2025-02-09 02:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0180_legacybasemodel_is_interregional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortfallBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Letter_date', models.DateField(blank=True, default=None, null=True)),
                ('Due_date', models.DateField(blank=True, default=None, null=True)),
                ('Entity', models.TextField(default=None)),
                ('Final_charges', models.FloatField(blank=True, default=None)),
                ('Fin_code', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'shortfall_basemodel',
                'unique_together': {('Letter_date', 'Fin_code', 'Entity')},
            },
        ),
        migrations.CreateModel(
            name='ShortfallPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid_date', models.DateField(default=None)),
                ('Description', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('Paid_amount', models.FloatField(blank=True)),
                ('Other_info', models.TextField(blank=True, default=None, null=True)),
                ('Bank_type', models.CharField(blank=True, default=None, null=True)),
                ('approved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paystatus_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsm.shortfallbasemodel')),
            ],
            options={
                'db_table': 'shortfall_payments',
                'unique_together': {('Paid_date', 'Description', 'Paid_amount', 'paystatus_fk')},
            },
        ),
    ]
