# Generated by Django 4.2.11 on 2025-02-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0181_shortfallbasemodel_shortfallpayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortfallpayments',
            old_name='Paid_date',
            new_name='Paid_date1',
        ),
    ]
