# Generated by Django 4.2.11 on 2025-02-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0182_rename_paid_date_shortfallpayments_paid_date1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortfallpayments',
            old_name='Paid_date1',
            new_name='Paid_date',
        ),
        migrations.AlterUniqueTogether(
            name='shortfallpayments',
            unique_together={('Paid_date', 'Description', 'Paid_amount', 'paystatus_fk')},
        ),
    ]
