# Generated by Django 4.2.11 on 2025-02-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0183_rename_paid_date1_shortfallpayments_paid_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortfallbasemodel',
            old_name='Letter_date',
            new_name='Letter_date1',
        ),
    ]
