# Generated by Django 4.2.11 on 2025-02-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0184_rename_letter_date_shortfallbasemodel_letter_date1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortfallbasemodel',
            old_name='Letter_date1',
            new_name='Letter_date',
        ),
        migrations.RemoveField(
            model_name='shortfallpayments',
            name='Paid_date',
        ),
        migrations.AddField(
            model_name='shortfallpayments',
            name='Paid_date1',
            field=models.DateField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='shortfallbasemodel',
            unique_together={('Letter_date', 'Fin_code', 'Entity')},
        ),
    ]
