# Generated by Django 4.2.11 on 2025-02-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0185_rename_letter_date1_shortfallbasemodel_letter_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortfallpayments',
            name='Paid_date1',
        ),
        migrations.AddField(
            model_name='shortfallpayments',
            name='Paid_date',
            field=models.DateField(default=None),
        ),
    ]
