# Generated by Django 4.2.11 on 2025-02-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0186_remove_shortfallpayments_paid_date1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortfallpayments',
            name='Is_disbursed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
