# Generated by Django 4.2.11 on 2025-02-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0187_shortfallpayments_is_disbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortfallbasemodel',
            name='Fin_year',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
