# Generated by Django 4.2.11 on 2025-02-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0188_shortfallbasemodel_fin_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCUCCCBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Letter_date', models.DateField(blank=True, default=None, null=True)),
                ('Entity', models.TextField(default=None)),
                ('Final_charges', models.FloatField(blank=True, default=None)),
                ('Fin_code', models.CharField(default=None, max_length=100)),
                ('PayableorReceivable', models.CharField(blank=True, default=None, max_length=50)),
            ],
            options={
                'db_table': 'scuc_cc_basemodel',
                'unique_together': {('Letter_date', 'Fin_code', 'Entity')},
            },
        ),
    ]
