# Generated by Django 4.2.11 on 2025-03-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0189_scucccbasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scucccbasemodel',
            name='Fin_year',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
