# Generated by Django 4.2.11 on 2025-03-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0190_scucccbasemodel_fin_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='scucccbasemodel',
            name='up_to_the_month',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
