# Generated by Django 4.2.11 on 2025-04-17 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0191_scucccbasemodel_up_to_the_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconUploadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acc_type', models.CharField(default=None, max_length=15)),
                ('Fin_year', models.CharField(blank=True, max_length=15)),
                ('Quarter', models.CharField(blank=True, max_length=5)),
                ('Fin_code', models.CharField(blank=True, max_length=10)),
                ('Upload_status', models.CharField(default=None, max_length=5)),
                ('Uploaded_time', models.DateTimeField(default=datetime.datetime(2025, 4, 17, 12, 31, 26, 962013))),
                ('File_path', models.TextField(default=None)),
                ('Admin_remarks', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Admin_uploaded_time', models.DateTimeField(default=datetime.datetime(2025, 4, 17, 12, 31, 26, 962013))),
            ],
            options={
                'db_table': 'recon_uploadstatus',
                'unique_together': {('Fin_year', 'Quarter', 'Fin_code', 'Upload_status')},
            },
        ),
        migrations.CreateModel(
            name='ReconNotified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acc_type', models.CharField(default=None, max_length=15)),
                ('Fin_year', models.CharField(blank=True, max_length=15)),
                ('Quarter', models.CharField(blank=True, max_length=5)),
                ('Notified_date', models.DateField(default=datetime.date(2025, 4, 17))),
            ],
            options={
                'db_table': 'recon_notified',
                'unique_together': {('Acc_type', 'Fin_year', 'Quarter')},
            },
        ),
    ]
