# Generated by Django 4.2.11 on 2025-04-30 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0192_excessbasemodel_disbursed_date_reconuploadstatus_and_more'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='ReconLastQuarterBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acc_type', models.CharField(default=None, max_length=15)),
                ('Fin_year', models.CharField(blank=True, max_length=15)),
                ('Quarter', models.CharField(blank=True, max_length=5)),
                ('Amount', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'recon_lastquarterbalance',
                'unique_together': {('Acc_type', 'Fin_year', 'Quarter')},
            },
        ),
    ]
