# Generated by Django 4.2.11 on 2025-04-30 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0193_alter_excessbasemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excessbasemodel',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='reconlastquarterbalance',
            name='Fin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='reconnotified',
            name='Notified_date',
            field=models.DateField(default=datetime.date(2025, 4, 30)),
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Admin_uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 11, 18, 2, 577970)),
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 11, 18, 2, 577970)),
        ),
    ]
