# Generated by Django 4.2.11 on 2025-04-30 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0194_alter_excessbasemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Admin_uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 12, 11, 12, 867806)),
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 12, 11, 12, 867806)),
        ),
        migrations.AlterUniqueTogether(
            name='reconlastquarterbalance',
            unique_together={('Acc_type', 'Fin_year', 'Quarter', 'Fin_code')},
        ),
    ]
