# Generated by Django 4.2.11 on 2025-06-13 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0195_alter_reconuploadstatus_admin_uploaded_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excessbasemodel',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='dsmreceivables',
            name='is_revision',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='is_revision',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='reconlastquarterbalance',
            name='as_on_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reconnotified',
            name='Notified_date',
            field=models.DateField(default=datetime.date(2025, 6, 13)),
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Admin_uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 16, 38, 37, 699095)),
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 16, 38, 37, 699095)),
        ),
        migrations.AlterUniqueTogether(
            name='netasbasemodel',
            unique_together={('Fin_year', 'Week_no', 'Entity', 'Revision_no', 'Final_charges')},
        ),
        migrations.AlterUniqueTogether(
            name='reacbasemodel',
            unique_together={('Fin_year', 'Week_no', 'Entity', 'Revision_no', 'Final_charges')},
        ),
    ]
