# Generated by Django 4.2.11 on 2025-06-13 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0199_alter_reconuploadstatus_admin_uploaded_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='is_revision',
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Admin_uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 16, 49, 2, 749049)),
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 16, 49, 2, 749049)),
        ),
    ]
