# Generated by Django 4.2.11 on 2025-06-13 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0201_payments_is_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsmreceivables',
            name='is_revision',
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Admin_uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 16, 50, 59, 685017)),
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 16, 50, 59, 685017)),
        ),
    ]
