# Generated by Django 4.2.11 on 2025-06-13 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0202_remove_dsmreceivables_is_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsmreceivables',
            name='is_revision',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Admin_uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 16, 51, 29, 174360)),
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 16, 51, 29, 174360)),
        ),
    ]
