# Generated by Django 4.2.11 on 2025-06-16 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsm', '0203_dsmreceivables_is_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconnotified',
            name='Notified_date',
            field=models.DateField(default=datetime.date(2025, 6, 16)),
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Admin_uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 17, 20, 31, 872506)),
        ),
        migrations.AlterField(
            model_name='reconuploadstatus',
            name='Uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 17, 20, 31, 872506)),
        ),
    ]
